### ISSUE TITLE
CrashHandler: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintManager;

### ISSUE THREAD

**Issue by MichealMike** [nshmura/RecyclerTabLayout#18]
06-29 10:47:50.354 23962-23962/cn.com.kpcq.xunjian.jinan E/CrashHandler: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintManager;
                                                                             at com.nshmura.recyclertablayout.RecyclerTabLayout$DefaultAdapter.onCreateViewHolder(RecyclerTabLayout.java:479)
                                                                             at com.nshmura.recyclertablayout.RecyclerTabLayout$DefaultAdapter.onCreateViewHolder(RecyclerTabLayout.java:435)

line      479

  if (mTabBackgroundResId != 0) {
                tabTextView.setBackgroundDrawable(
  479                      TintManager.getDrawable(tabTextView.getContext(), mTabBackgroundResId));
            }

**Comment by nshmura** [comment]
This issue was fixed.
Please update to latest version.
```
   compile 'com.nshmura:recyclertablayout:1.0.0'
```
